steps:
- id: pull-node-modules-image
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
     docker pull gcr.io/$_PROJECT_ID/$REPO_NAME-packages:$BRANCH_NAME || exit 0
  waitFor: ["-"]

- id: build-packages-image
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker build \
    --target package \
    -t gcr.io/$_PROJECT_ID/$REPO_NAME-packages:$BRANCH_NAME \
    --cache-from gcr.io/$_PROJECT_ID/$REPO_NAME-packages:$BRANCH_NAME .

- id: push-new-packages-image
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker push gcr.io/$_PROJECT_ID/$REPO_NAME-packages:$BRANCH_NAME

- id: build-images
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  volumes:
    - name: 'vol1'
      path: '/dist'
  args:
  - '-c'
  - |
    docker build \
    -t gcr.io/$_PROJECT_ID/$REPO_NAME:$BRANCH_NAME-$BUILD_ID \
    -t gcr.io/$_PROJECT_ID/$REPO_NAME:$BRANCH_NAME \
    -t gcr.io/$_PROJECT_ID/$REPO_NAME:latest \
    --build-arg DEPLOY_ENV=${_DEPLOY_ENV} \
    --cache-from gcr.io/$_PROJECT_ID/$REPO_NAME-packages:$BRANCH_NAME .

    docker run -d --name gaea gcr.io/$_PROJECT_ID/$REPO_NAME:$BRANCH_NAME sleep 1000
    docker cp gaea:/app/dashboard/ /dist/

- id: copy file
  name: google/cloud-sdk:slim
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gsutil -m rsync -r /dist/dashboard gs://gaea-static-prod/admin/static
  volumes:
    - name: 'vol1'
      path: '/dist'

- id: push-images
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker push gcr.io/$_PROJECT_ID/$REPO_NAME:$BRANCH_NAME-$BUILD_ID
    docker push gcr.io/$_PROJECT_ID/$REPO_NAME:$BRANCH_NAME
    # docker push gcr.io/$_PROJECT_ID/$REPO_NAME:latest

- id: deploy
  name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud beta run deploy $REPO_NAME-${_DEPLOY_ENV} \
    --image gcr.io/${_PROJECT_ID}/$REPO_NAME:${_DEPLOY_ENV}-$BUILD_ID \
    --platform managed \
    --allow-unauthenticated \
    --service-account gaea-cloudrun-sa@${_PROJECT_ID}.iam.gserviceaccount.com \
    --region us-central1 \
    --vpc-connector ${_VPC} \
    --ingress ${_INGRESS} \
    --vpc-egress ${_EGRESS} \
    --min-instances ${_MIN} \
    --cpu 1 \
    --memory 2Gi \
    --port 80 \
    --labels=project=funpinpin,service=gaea,module=${_MODULE},env=${_DEPLOY_ENV} \
    --project ${_PROJECT_ID}
substitutions:
  _PROJECT_ID: papaya-store-prod
options:
  machineType: 'N1_HIGHCPU_8'
timeout: 1200s
