export default [
    {
      title:'Roboto',
      value:[
        {
          label:'标准',
          value:'Roboto-Regular'
        },
        {
          label:'细斜体',
          value:'Roboto-LightItalic'
        },
        {
          label:'细体',
          value:'Roboto-Light'
        },
        {
          label:'特细斜体',
          value:'Roboto-ThinItalic'
        },
        {
          label:'特细体',
          value:'Roboto-Thin'
        },
        {
          label:'次粗斜体',
          value:'Roboto-MediumItalic'
        },
        {
          label:'次粗体',
          value:'Roboto-Medium'
        },
        {
          label:'斜体',
          value:'Roboto-Italic'
        },
        {
          label:'粗斜体',
          value:'Roboto-BoldItalic'
        },
        {
          label:'粗体',
          value:'Roboto-Bold'
        },
        {
          label:'特粗斜体',
          value:'Roboto-BlackItalic'
        },
        {
          label:'特粗体',
          value:'Roboto-Black'
        },
        
      ]
    },
    {
      title:'Lato',
      value:[
        {
          label:'标准',
          value:'Lato-Regular'
        },
        {
          label:'细斜体',
          value:'Lato-LightItalic'
        },
        {
          label:'细体',
          value:'Lato-Light'
        },
        {
          label:'斜体',
          value:'Lato-Italic'
        },
        {
          label:'特细斜体',
          value:'Lato-HairlineItalic'
        },
        {
          label:'特细体',
          value:'Lato-Hairline'
        },
        {
          label:'粗斜体',
          value:'Lato-BoldItalic'
        },
        {
          label:'粗体',
          value:'Lato-Bold'
        },
        {
          label:'特粗斜体',
          value:'Lato-BlackItalic'
        },
        {
          label:'特粗体',
          value:'Lato-Black'
        },
      ]
    },
    {
      title:'PT_Sans',
      value:[
        {
          label:'标准',
          value:'PT_Sans-Web-Regular'
        },
        {
          label:'斜体',
          value:'PT_Sans-Web-Italic'
        },
        {
          label:'粗斜体',
          value:'PT_Sans-Web-BoldItalic'
        },
        {
          label:'粗体',
          value:'PT_Sans-Web-Bold'
        },
      ]
    },
    {
      title:'Montserrat',
      value:[
        {
          label:'标准',
          value:'Montserrat-Regular'
        },
        {
          label:'细斜体',
          value:'Montserrat-LightItalic'
        },
        {
          label:'细体',
          value:'Montserrat-Light'
        },
        {
          label:'特细斜体',
          value:'Montserrat-ThinItalic'
        },
        {
          label:'特细体',
          value:'Montserrat-Thin'
        },
        {
          label:'次细斜体',
          value:'Montserrat-ExtraLightItalic'
        },
        {
          label:'次细体',
          value:'Montserrat-ExtraLight'
        },
        {
          label:'次粗斜体',
          value:'Montserrat-MediumItalic'
        },
        {
          label:'次粗体',
          value:'Montserrat-Medium'
        },
        {
          label:'粗斜体',
          value:'Montserrat-SemiBoldItalic'
        },
        {
          label:'粗体',
          value:'Montserrat-SemiBold'
        },
        {
          label:'加粗斜体',
          value:'Montserrat-ExtraBoldItalic'
        },
        {
          label:'加粗体',
          value:'Montserrat-ExtraBold'
        },
        {
          label:'特粗斜体',
          value:'Montserrat-BlackItalic'
        },
        {
          label:'特粗体',
          value:'Montserrat-Black'
        },

      ]
    },
    {
      title:'RobotoCondensed',
      value:[
        {
          label:'标准',
          value:'RobotoCondensed-Regular'
        },
        {
          label:'细斜体',
          value:'RobotoCondensed-LightItalic'
        },
        {
          label:'细体',
          value:'RobotoCondensed-Light'
        },
        {
          label:'斜体',
          value:'RobotoCondensed-Italic'
        },
        {
          label:'粗斜体',
          value:'RobotoCondensed-BoldItalic'
        },
        {
          label:'粗体',
          value:'RobotoCondensed-Bold'
        },
      ]
    },
    {
      title:'Yantramanav',
      value:[
        {
          label:'标准',
          value:'Yantramanav-Regular'
        },
        {
          label:'细体',
          value:'Yantramanav-Light'
        },
        {
          label:'特细体',
          value:'Yantramanav-Thin'
        },
        {
          label:'粗体',
          value:'Yantramanav-Bold'
        },
        {
          label:'特粗体',
          value:'Yantramanav-Black'
        },
      ]
    },
    {
      title:'Rajdhani',
      value:[
        {
          label:'标准',
          value:'Rajdhani-Regular'
        },
        {
          label:'细体',
          value:'Rajdhani-Light'
        },
        {
          label:'次粗体',
          value:'Rajdhani-Medium'
        },
        {
          label:'中粗体',
          value:'Rajdhani-SemiBold'
        },
        {
          label:'粗体',
          value:'Rajdhani-Bold'
        },
      ]
    },
    {
      title:'Merriweather',
      value:[
        {
          label:'标准',
          value:'Merriweather-Regular'
        },
        {
          label:'细斜体',
          value:'Merriweather-LightItalic'
        },
        {
          label:'细体',
          value:'Merriweather-Light'
        },
        {
          label:'斜体',
          value:'Merriweather-Italic'
        },
        {
          label:'粗斜体',
          value:'Merriweather-BoldItalic'
        },
        {
          label:'粗体',
          value:'Merriweather-Bold'
        },
        {
          label:'特粗斜体',
          value:'Merriweather-BlackItalic'
        },
        {
          label:'特粗体',
          value:'Merriweather-Black'
        },
      ]
    },
    {
      title:'Libre_Baskerville',
      value:[
        {
          label:'标准',
          value:'Libre_Baskerville-Regular'
        },
        {
          label:'斜体',
          value:'Libre_Baskerville-Italic'
        },
        {
          label:'粗体',
          value:'Libre_Baskerville-Bold'
        },
      ]
    },
    {
      title:'Vidaloka',
      value:[
        {
          label:'标准',
          value:'Vidaloka-Regula'
        },
      ]
    },
    {
      title:'NotoSerif',
      value:[
        {
          label:'标准',
          value:'NotoSerif-Regular'
        },
        {
          label:'斜体',
          value:'NotoSerif-Italic'
        },
        {
          label:'粗斜体',
          value:'NotoSerif-BoldItalic'
        },
        {
          label:'粗体',
          value:'NotoSerif-Bold'
        },
      ]
    },
    {
      title:'PT_Serif_Caption',
      value:[
        {
          label:'标准',
          value:'PT_Serif-Caption-Web-Regular'
        },
        {
          label:'斜体',
          value:'PT_Serif-Caption-Web-Italic'
        },
      ]
    },
    {
      title:'PT_Serif',
      value:[
        {
          label:'标准',
          value:'PT_Serif-Web-Regular'
        },
        {
          label:'斜体',
          value:'PT_Serif-Web-Italic'
        },
        {
          label:'粗斜体',
          value:'PT_Serif-Web-BoldItalic'
        },
        {
          label:'粗体',
          value:'PT_Serif-Web-Bold'
        },
      ]
    },
    {
      title:'Crete_Round',
      value:[
        {
          label:'标准',
          value:'Crete_Round-Regular'
        },
        {
          label:'斜体',
          value:'Crete_Round-Italic'
        },
      ]
    },
    {
      title:'Itim',
      value:[
        {
          label:'标准',
          value:'Itim-Regular'
        },
      ]
    },
    {
      title:'Expletus_Sans',
      value:[
        {
          label:'标准',
          value:'Expletus_Sans-Regular'
        },
        {
          label:'斜体',
          value:'Expletus_Sans-Italic'
        },
        {
          label:'次粗斜体',
          value:'Expletus_Sans-MediumItalic'
        },
        {
          label:'次粗体',
          value:'Expletus_Sans-Medium'
        },
        {
          label:'较粗斜体',
          value:'Expletus_Sans-SemiBoldItalic'
        },
        {
          label:'较粗体',
          value:'Expletus_Sans-SemiBold'
        },
        {
          label:'粗斜体',
          value:'Expletus_Sans-BoldItalic'
        },
        {
          label:'粗体',
          value:'Expletus_Sans-Bold'
        },
      ]
    },
    {
      title:'Baloo_Bhai_2',
      value:[
        {
          label:'常规体',
          value:'Baloo_Bhai_2-Regular'
        },
        {
          label:'中黑',
          value:'Baloo_Bhai_2-Medium'
        },
        {
          label:'中粗体',
          value:'Baloo_Bhai_2-SemiBold'
        },
        {
          label:'粗体',
          value:'Baloo_Bhai_2-Bold'
        },
        {
          label:'加粗体',
          value:'Baloo_Bhai_2-ExtraBold'
        },
      ]
    },
    {
      title:'Archivo',
      value:[
        {
          label:'标准',
          value:'Archivo-Regular'
        },
        {
          label:'斜体',
          value:'Archivo-Italic'
        },
        {
          label:'次粗斜体',
          value:'Archivo-MediumItalic'
        },
        {
          label:'次粗体',
          value:'Archivo-Medium'
        },
        {
          label:'粗斜体',
          value:'Archivo-BoldItalic'
        },
        {
          label:'粗体',
          value:'Archivo-Bold'
        },
        {
          label:'加粗斜体',
          value:'Archivo-SemiBoldItalic'
        },
        {
          label:'加粗体',
          value:'Archivo-SemiBold'
        },
      ]
    },
    {
      title:'Karla',
      value:[
        {
          label:'标准',
          value:'Karla-Regular'
        },
        {
          label:'斜体',
          value:'Karla-Italic'
        },
        {
          label:'粗斜体',
          value:'Karla-BoldItalic'
        },
        {
          label:'粗体',
          value:'Karla-Bold'
        },
      ]
    },
    {
      title:'MavenPro',
      value:[
        {
          label:'标准',
          value:'MavenPro-Regular'
        },
        {
          label:'次粗体',
          value:'MavenPro-Medium'
        },
        {
          label:'粗体',
          value:'MavenPro-Bold'
        },
        {
          label:'特粗体',
          value:'MavenPro-Black'
        },
      ]
    },
    
    {
      title:'Questrial',
      value:[
        {
          label:'标准',
          value:'Questrial-Regular'
        },
      ]
    },
    {
      title:'Scheherazade',
      value:[
        {
          label:'标准',
          value:'Scheherazade-Regular'
        },
        {
          label:'粗体',
          value:'Scheherazade-Bold'
        },
      ]
    },
    {
      title:'SpecialElite',
      value:[
        {
          label:'标准',
          value:'SpecialElite-Regular',
        },
      ]
    },
    {
      title:'Spectral',
      value:[
        {
          label:'标准',
          value:'Spectral-Regular'
        },
        {
          label:'细斜体',
          value:'Spectral-LightItalic'
        },
        {
          label:'细体',
          value:'Spectral-Light'
        },
        {
          label:'斜体',
          value:'Spectral-Italic'
        },
        {
          label:'次细斜体',
          value:'Spectral-ExtraLightItalic'
        },
        {
          label:'次细体',
          value:'Spectral-ExtraLight'
        },
        {
          label:'次粗斜体',
          value:'Spectral-MediumItalic'
        },
        {
          label:'次粗体',
          value:'Spectral-Medium'
        },
        {
          label:'粗斜体',
          value:'Spectral-BoldItalic'
        },
        {
          label:'粗体',
          value:'Spectral-Bold'
        },
        {
          label:'加粗斜体',
          value:'Spectral-SemiBoldItalic'
        },
        {
          label:'加粗体',
          value:'Spectral-SemiBold'
        },
        {
          label:'特粗斜体',
          value:'Spectral-ExtraBoldItalic'
        },
        {
          label:'特粗体',
          value:'Spectral-ExtraBold'
        },
      ]
    },
  ]